services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test:
        - CMD
        - pg_isready
        - -U
        - $$POSTGRES_USER
        - -d
        - $$POSTGRES_DB
      interval: 5s
      timeout: 5s
      retries: 30
      start_period: 10s
    networks:
      - taski_net
    restart: always

  backend:
    image: pavellchemakin/taski_backend:latest
    env_file: .env
    volumes:
      - static:/backend_static
      - media:/media
    depends_on:
      db:
        condition: service_healthy
    networks:
      - taski_net
    restart: always

  frontend:
    image: pavellchemakin/taski_frontend:latest
    env_file: .env
    volumes:
      - static:/static
    networks:
      - taski_net
    restart: always

  gateway:
    image: pavellchemakin/taski_gateway:latest
    env_file: .env
    volumes:
      - static:/static
      - media:/media
      - ./gateway/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "127.0.0.1:9001:80"
    depends_on:
      - backend
      - frontend
    networks:
      - taski_net
    restart: always

volumes:
  pg_data:
  static:
  media:

networks:
  taski_net:
