services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready -U "$POSTGRES_USER" -d "$POSTGRES_DB" -h 127.0.0.1 -p 5432
      interval: 5s
      timeout: 5s
      retries: 12
      start_period: 20s
    networks:
      - taski_net
    restart: always

  backend:
    image: pavellchemakin/taski_backend:latest
    env_file: .env
    volumes:
      - static:/backend_static
      - media:/app/media
    depends_on:
      db:
        condition: service_healthy
    expose:
      - "8000"
    healthcheck:
      test:
        - CMD-SHELL
        - |
          python - <<'PY'
          import socket, sys
          s = socket.socket()
          s.settimeout(2)
          try:
              s.connect(("127.0.0.1", 8000))
          except Exception:
              sys.exit(1)
          else:
              print("ok")
              sys.exit(0)
          finally:
              s.close()
          PY
      interval: 10s
      timeout: 3s
      retries: 10
    networks:
      - taski_net
    restart: always

  frontend:
    image: pavellchemakin/taski_frontend:latest
    env_file: .env
    volumes:
      - static:/static
    expose:
      - "8000"
    networks:
      - taski_net
    restart: always

  gateway:
    image: pavellchemakin/taski_gateway:latest
    env_file: .env
    depends_on:
      backend:
        condition: service_healthy
      frontend:
        condition: service_started
    ports:
      - "127.0.0.1:9001:80"
    volumes:
      - static:/static
      - media:/media
    networks:
      - taski_net
    restart: always

volumes:
  pg_data:
  static:
  media:

networks:
  taski_net:
